name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - run: npm i -g yarn
      - run: yarn
      - run: yarn build
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - run: npm i -g yarn
      - run: yarn
      - run: yarn lint
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - run: npm i -g yarn
      - run: yarn
      - run: yarn test
  publish:
    if: github.ref == 'refs/heads/master'
    needs: ['build', 'test']
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
      - run: yarn
      - run: yarn build
      - run: NPM_AUTH_TOKEN=${{ secrets.NPM_AUTH_TOKEN }} yarn run lerna run publish from-package
  tag:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Tag
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag @routerating/requests
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "@routerating/requests@v"
          root: "packages/requests/package.json"
      - name: Tag @routerating/interfaces
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "@routerating/interfaces@v"
          root: "packages/entities/package.json"
      - name: Tag @routerating/web
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "@routerating/web@v"
          root: "apps/web/package.json"
